---


  gather_facts: no
  connection: local

  tasks:
    - name: run show command on remote devices
      ios_command:
        commands:
          - show version
        provider: "{{ cli }}"
      register: result
    - debug: var=result

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_username }}"
      password: "{{ ansible_password }}"
      authorize: true
      auth_pass: "{{ enable_secret }}"
